### ISSUE TITLE
误导性描述

### ISSUE THREAD

**Issue by FrankHB** [sdlddr/Gooflow#21]
1L喂repo主（鉴于已有修改不留记录的前科）。

**Comment by FrankHB** [comment]
`如果逃避购买授权，擅自窃取用作谋利，即属严重侵权行为，与盗窃无异。`

是哪个管辖的法律允许本项目修改和覆盖著作权侵犯和/或盗窃行为的法定外延的？

**Comment by sdlddr** [comment]
别拿你的智商秀下限，垃圾

**Comment by FrankHB** [comment]
> 别拿你的智商秀下限，垃圾

似乎是法盲和流氓定谳了？

**Comment by FrankHB** [comment]
`1L喂repo主（鉴于已有修改不留记录的前科）。`

@sdlddr sdlddr changed the title from 误导性描述 to —— 6 minutes ago

对号入座倒是挺实诚的……
