### ISSUE TITLE
刚听说,我来看看发现你关闭了 issues

### ISSUE THREAD

**Issue by yoyojacky** [sdlddr/Gooflow#25]
听说你这边开了 MIT 协议然后又赤裸裸在代码里面加入了挖矿的代码啊? 
不是说好 MIT 是开源, 可以用于非盈利么...
另外,你让我看完再删 issues 行不行,我是围观群众...

**Comment by yelvlab** [comment]
同刚听说，怎么发现issue都关了，名字还都改成下划线，不过好在不多，这个是25可以从1到25一个个看

**Comment by yoyojacky** [comment]
具体是什么情况啊? 不明真相的吃瓜群众.....
我同事说这边出大事儿了.我以为是什么大事儿呢...
原来是因为版权的问题啊....

**Comment by yoyojacky** [comment]
听说还投毒了?

**Comment by XadillaX** [comment]
@yoyojacky 不是版权问题，版权问题是事发后临时改的，之前一直是 MIT。

**Comment by yoyojacky** [comment]
what the fuck? 
为啥直接关闭啦...都没有回答我啊!

**Comment by yoyojacky** [comment]
哦, MIT 协议不是都可以用么? 怎么突然要收费还是咋地?

**Comment by Liam0205** [comment]
他在代码中嵌入了使用客户端机器进行挖矿牟利的恶意代码。

**Comment by XadillaX** [comment]
@yoyojacky 因为里面有挖矿代码，碍不下面子改了收费并说你们都是盗版用户，用了有挖矿代码的库是应该的。

**Comment by yoyojacky** [comment]
还听说嵌入挖矿的代码了? 这么狠~
哎,人家也不容易,写个代码挺费劲的.大家就都散了吧.

**Comment by yoyojacky** [comment]
我操,这么屌的操作真是 six six six 啊!

**Comment by yoyojacky** [comment]
反正我不用他的代码,我只是过来围观的. 这波操作真是6~哈哈 ...

**Comment by liyinkan** [comment]
![image](https://user-images.githubusercontent.com/693349/41035908-c652fc4e-69c0-11e8-89c5-4121de073e11.png)

**Comment by sdlddr** [comment]
@liyinkan 以前的也是差不多的

**Comment by sdlddr** [comment]
原来一直是用： MIT+MIT里允许的自定义修改协议，并对试用版的使用作了警告。
