### ISSUE TITLE
能支持bpmn2.0并且生成xml格式的产物就好了

### ISSUE THREAD

**Issue by purecreek** [sdlddr/Gooflow#3]
能支持bpmn2.0并且生成xml格式的产物就好了。作者有没有这样的打算，这样的话就能和国际标准接轨了

**Comment by sdlddr** [comment]
目前流程图的XML标准很多，前端UI不好做处理，才用了JSON格式，由客户自行在后端进行JSON解析。后端解析效率比JS转换更高，AJAX传输数据量上JSON也是最少的

**Comment by purecreek** [comment]
支持bpmn2.0是个大的趋势。不过个人项目去搞这个工作量上面太大了。我也是比较喜欢json的。但是好多开源的工作流引擎都有直接解析bpmn2.0 标准的xml 的实现。我倒希望能多来一些大神，一起把这块给这个插件开发一套生成xml产物的api。希望这个插件能流行起来

**Comment by sdlddr** [comment]
理论上来说，用JS来实现json与bpmn2.0的互转不成问题，只是要有人有时间去做
