### ISSUE TITLE
这个项目存在隐藏挖矿代码

### ISSUE THREAD

**Issue by wujx608** [sdlddr/Gooflow#6]
这个项目中存在 隐藏的代码。
请各位使用者注意！

**Comment by sdlddr** [comment]
这是专门给那些只知道免费拿别人的成果，再用来给自己营利，无视购买商业使用授权的伸手党的一份大礼包。而且仅仅是消耗掉了大半CPU资源，并不是100%，实际使用影响仅是使用该组件时系统变慢。是异步消耗，并不会像JS循环代码那样让电脑陷入空转假死。真正购买了商业使用授权的用户才能得到性能优化的纯净版本。
