### ISSUE TITLE
提示样式

### ISSUE THREAD

**Issue by wing-only** [sdlddr/Gooflow#9]
查看模式下，鼠标放到某个节点上有提示效果吗？

**Comment by sdlddr** [comment]
这个没做开发，你可以自己做扩展的

**Comment by wing-only** [comment]
有预留扩展接口，可否提示一下，谢谢。

**Comment by sdlddr** [comment]
你可以自己找第三方提示控件，绑定到节点dom上面的。
API文档上的自定义扩展章节中，你可以自己开发新方法接口。
